import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

function TopNav() {
  return (
    <nav className="flex w-full items-center justify-between bg-[#462B15] p-4 text-xl font-semibold border-b">
      <h1 className="text-2xl text-white pr-2">Gallery</h1>
      <h1 className="text-2xl text-white pl-4">Sign In</h1>
    </nav>
  );
}
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="flex flex-col gap-1">
        <TopNav />
        {children}
      </body>
    </html>
  );
}
